### ISSUE TITLE
Possible issue with python3

### ISSUE THREAD

**Issue by GiovanniBussi** [srnas/barnaba#13]
I am trying to use barnaba with MacPorts python (I don't like conda).

(I actually just opened a [pull request](https://github.com/macports/macports-ports/pull/1315) to include mdtraj in MacPorts, so all the requirements will be there soon. The long term plan is to include barnaba in MacPorts as well).

If I try to launch baRNAba.py from the command line with python2.7 it works:
````
macbook: (master) barnaba$ PYTHONPATH=/Users/bussi/barnaba/ python2.7 bin/baRNAba.py
usage: baRNAba.py [-h]
                  {ERMSD,RMSD,ESCORE,SS_MOTIF,DS_MOTIF,ANNOTATE,DUMP,TORSION,JCOUPLING,SNIPPET,ENM}
                  ...
baRNAba.py: error: too few arguments
````

However, if I launch it with python3.6 it does not work:
````
macbook: (master) barnaba$ PYTHONPATH=/Users/bussi/barnaba/ python3.6 bin/baRNAba.py
Traceback (most recent call last):
  File "bin/baRNAba.py", line 582, in <module>
    main()
  File "bin/baRNAba.py", line 552, in main
    outfile = filename(args)
  File "bin/baRNAba.py", line 540, in filename
    if(args.name == None):
AttributeError: 'Namespace' object has no attribute 'name'
````

I suspect there is a problem with py27 to py36 conversion, but my ignorance does not allow me to fix it (or to even be sure that this is the reason...). Notice that it only happens when passing no argument (e.g. `.... bin/baRNAba.py ENM` works).

Perhaps @wouterboomsma could have a look?

Thanks!

Giovanni

**Comment by wouterboomsma** [comment]
Apparently, it was due to some internal change they made to argparse: https://stackoverflow.com/questions/23349349/argparse-with-required-subparser. I've now explicitly made the subparser a required option as suggested there, which means it now fails both in Python2 and Python3 when no subparser argument is provided.

**Comment by GiovanniBussi** [comment]
Thanks!
