### ISSUE TITLE
ENM example does not work

### ISSUE THREAD

**Issue by sbottaro** [srnas/barnaba#25]
When I run the ENM example within jupyter I get the following error:

/Users/sandrobottaro/anaconda/lib/python2.7/site-packages/mdtraj/core/selection.pyc in __call__(self, selection)
    352             lines = ["%s: %s" % (msg, selection),
    353                      " " * (12 + len("%s: " % msg) + e.loc) + "^^^"]
--> 354             raise ValueError('\n'.join(lines))
    355 
    356         # Change __ATOM__ in function bodies. It must bind to the arg

ValueError: Expected end of text (at char 11), (line:1, col:12): name "C1'" "C2" "P" "CA" "CB"

**Comment by giopina** [comment]
I tried also with Python 2.7 and I don't get any error message.

In which cell does this happen?

**Comment by sbottaro** [comment]
Apparently it is a problem with MDtraj. Updating to mdtraj 1.9 solves the problem.
