### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by GiovanniBussi** [srnas/barnaba#36]
@sbottaro can you make a new release on pip?

I think there are important fixes on ENM. Tests are failing with 0.1.5 but do work with master. (cc: @giopina)

Thanks!

Giovanni

**Comment by sbottaro** [comment]
I have just created a new release, that includes new examples. Let me know if you experience problems

**Comment by GiovanniBussi** [comment]
@sbottaro thanks now also MacPorts is up to date! I changed it to download files from github, so that having tagged versions on github will be sufficient
