### ISSUE TITLE
Sparse ENMs

### ISSUE THREAD

**Issue by GiovanniBussi** [srnas/barnaba#4]
[This branch](https://github.com/srnas/barnaba/tree/sparse) implements sparse ENMs, where tools for sparse matrices are used. Results are equivalent but are significantly faster for large molecules. It might be worth integrating also these functions in the new version.

**Comment by giopina** [comment]
It will certainly be useful. I'll take a look at it now.

I never merged it into the master branch because I got stuck on the problem of computing the entropy (which comes from the determinant, and I didn't manage to find an efficient way to compute it). 
In the end, the entropy is not super useful, so we can include it as it is.

**Comment by giopina** [comment]
Now the branch [sparse-new](https://github.com/srnas/barnaba/tree/sparse-new) implements sparse matrices for ENM.

Tests seems to be working and compatible with the old version.

It also fixes some stuff in the ENM code and its tests.

**Comment by GiovanniBussi** [comment]
@sbottaro @giopina I am afraid this was not merged in time...

@giopina can you confirm that the code on the sparse-new branch is supposed to work correctly?

@wouterboomsma would it be possible to take care of merging it into master making the modified code compatible with python3? If the changes you made in 90da0bc30968b6f4609b3953363d8bd6c4acff12 are semiautomatic, perhaps it is not too difficult to reimplement them in the sparse-new branch. If you look at the code with
````
git diff origin/master...origin/sparse-new
````
you will see that most of the changes are in file ./barnaba/enm.py. In addition, there are changes to the tests that should be irrelevant here. Let me know if I can help in some way.

Thanks!

Giovanni

**Comment by wouterboomsma** [comment]
Sure, no problem. I'll take a look at it.

**Comment by giopina** [comment]
@GiovanniBussi The sparse-new branch passed all tests I performed.
All edits to the code are in the enm.py part (except an additional argument in barnaba.py), and I also edited the test on the enm part.

**Comment by giopina** [comment]
I'm actually a bit confused.
@sbottaro @GiovanniBussi Do you want me to take care of merging this with master? 
It think it should be merged. It works properly and there were a couple of bugs I fixed (like the Angstrom-nanometer confusion).

**Comment by GiovanniBussi** [comment]
@giopina if you know how to do it without breaking python3 stuff I think you can merge it. In any case, python3 is now tested on travis-ci.

**Comment by sbottaro** [comment]
It would be great if you could also create a notebook in the example section. I remember you had a way to visualize the modes in vmd and/or generate pdbs along the modes. Is that still possible/easy to do?

**Comment by giopina** [comment]
@GiovanniBussi I'll do the merging and test that everything runs with Python 3

@sbottaro possible, yes. Easy, I'm not sure. I can take a look a it

**Comment by giopina** [comment]
Done.
It passed all tests with nose and also on travis apprently..

**Comment by GiovanniBussi** [comment]
Great!
