### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by giopina** [srnas/barnaba#5]
I'm not sure what's the proper way to run all tests.
Should I just execute each of the test_*.py ?

**Comment by sbottaro** [comment]
you can run all the tests using nose

> pip install nose

and then run all of them from the root directory with the command

> nosetests

a single test can be also performed e.g.

> nosetests test/test_sugar.py

**Comment by sbottaro** [comment]
Since tests are very simple perhaps nose is not necessary, and we can thus avoid requiring another library. This should be very simple to do

**Comment by GiovanniBussi** [comment]
I think this can be closed now
